from fastapi import APIRouter, Depends
from sqlmodel import Session, select, func
from models.db import get_session, Candidate, JobMatch
from typing import List, Dict, Any
import json
from collections import Counter

router = APIRouter(prefix="/analytics", tags=["analytics"])

@router.get("/dashboard")
async def get_dashboard_stats(session: Session = Depends(get_session)):
    """
    Get aggregate statistics for the dashboard.
    """
    # Total candidates
    total_candidates = len(session.exec(select(Candidate)).all())
    
    # Match stats
    matches = session.exec(select(JobMatch)).all()
    total_matches = len(matches)
    
    avg_score = 0
    pass_rate = 0
    
    if total_matches > 0:
        avg_score = sum(m.match_score for m in matches) / total_matches
        passed_matches = sum(1 for m in matches if m.qualified)
        pass_rate = (passed_matches / total_matches) * 100
    
    return {
        "total_candidates": total_candidates,
        "total_matches": total_matches,
        "avg_match_score": round(avg_score, 1),
        "pass_rate": round(pass_rate, 1)
    }

@router.get("/skills")
async def get_skills_distribution(session: Session = Depends(get_session)):
    """
    Get distribution of skills across all candidates.
    Returns top 10 most common skills.
    """
    candidates = session.exec(select(Candidate)).all()
    
    all_skills = []
    for c in candidates:
        if c.skills:
            all_skills.extend(c.skills)
            
    # Count skills
    skill_counts = Counter(all_skills)
    
    # Get top 10
    top_skills = skill_counts.most_common(10)
    
    return {
        "skills": [{"name": skill, "count": count} for skill, count in top_skills]
    }

from fastapi.responses import StreamingResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

@router.get("/export")
async def export_report(session: Session = Depends(get_session)):
    """
    Generate and download a PDF report of the current dashboard stats.
    """
    # Fetch stats
    candidates = session.exec(select(Candidate)).all()
    matches = session.exec(select(JobMatch)).all()
    
    total_candidates = len(candidates)
    total_matches = len(matches)
    avg_score = 0
    pass_rate = 0
    if total_matches > 0:
        avg_score = sum(m.match_score for m in matches) / total_matches
        passed_matches = sum(1 for m in matches if m.qualified)
        pass_rate = (passed_matches / total_matches) * 100

    # Generate PDF
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, 750, "Recruitment Dashboard Report")
    
    # Stats
    c.setFont("Helvetica", 14)
    c.drawString(50, 700, f"Total Candidates: {total_candidates}")
    c.drawString(50, 680, f"Total Matches: {total_matches}")
    c.drawString(50, 660, f"Average Match Score: {avg_score:.1f}%")
    c.drawString(50, 640, f"Pass Rate: {pass_rate:.1f}%")
    
    c.drawString(50, 600, "Generated by AI Recruitment System")
    
    c.save()
    buffer.seek(0)
    
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=recruitment_report.pdf"}
    )
